### PR TITLE
add ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by tamascsaba**
I added ISSUE_TEMPLATE.md to easily create new issue (without copy old one).

### CODE REVIEW

**Review by presidento — CHANGES_REQUESTED** [review]
Please use, the unified/standard format. (Hint: there is no "Description" field.) You can create a `new_issue.sample` file based on the `https://github.com/balabit/coderegation/blob/gh-pages/_script/new_item.sample`. I suggest putting it on the same directory. And I suggest updating the documentation (the about page or the readme file) to share that there is an issue template somewhere.

**Comment by tamascsaba** [comment]
ISSUE_TEMPLATE.md file used by github. It is only work in base directory or in .github folder :)
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by presidento** [comment]
Sounds interesting.

Please, use _topic_ not, _title_, see the field names in the [new_item.sample](https://github.com/balabit/coderegation/blob/gh-pages/_script/new_item.sample). 

I suggest adding a sample description there, for example "_(Description comes here)_", but it can be fine for me this way, too.

**Review by presidento — APPROVED** [review]

**Comment by tamascsaba** [comment]
thx :+1:

**Comment by presidento** [comment]
Thank you very much! You got a :medal_sports: for the first pull request! :smile: Thank you again.

**Pull request merged**
